/**
 * Demo Mode — lets a visitor view Mission Control as if they ran one of the
 * nine business templates. Persists via cookie + URL query string so sales
 * links like `?demo=cpa` survive page reloads.
 *
 * This is intentionally lightweight: in demo mode we OVERLAY a curated story
 * (executive briefing, recent wins, attention items, value created) on the
 * existing UI. It does not mutate the live workspace database. The real
 * demo workspaces seeded by `scripts/seed-demo-workspace.ts` back the data
 * when the operator actually clicks through.
 */
import { BUSINESS_TEMPLATES, type BusinessTemplate } from './business-templates'
import type { AIEmployeeLifeSignal } from './ai-employee-life-signals'

export interface DemoNarrative {
  template: BusinessTemplate
  /** Headline that opens the Morning Briefing. */
  briefingHeadline: string
  /** Three "what happened today" wins. */
  dailyWins: { title: string; impact: string; valueUsd: number }[]
  /** What needs attention — surfaces in the Attention Required panel. */
  attentionItems: { title: string; severity: 'low' | 'medium' | 'high'; reason: string }[]
  /** Cumulative value-created counter (USD this month so far). */
  valueCreatedMonthUsd: number
  /** Hours saved this month (approximate). */
  hoursSavedMonth: number
  /** "What you should do next" — single primary action. */
  nextAction: { label: string; href: string }
  /** Star AI employee of the day. */
  topEmployee: { name: string; impact: string }
  /** AI Employee life signals — workforce-in-motion roster for the overview. */
  lifeSignals?: AIEmployeeLifeSignal[]
}

const NARRATIVES: Record<string, Omit<DemoNarrative, 'template'>> = {
  pm: {
    briefingHeadline: 'Quiet morning, two doors making noise.',
    dailyWins: [
      { title: 'Auto-dispatched 4 maintenance tickets', impact: '7 hours saved', valueUsd: 245 },
      { title: 'Sent monthly owner update for 14 properties', impact: '5 hours saved', valueUsd: 175 },
      { title: 'Caught a late rent payment before it cascaded', impact: '$280 recovered', valueUsd: 280 },
    ],
    attentionItems: [
      { title: 'Tenant complaint at 142 Elm escalated', severity: 'high', reason: 'AI flagged: tone analysis suggests legal-tier complaint.' },
      { title: 'Vendor at 88 Birch missed scheduled inspection', severity: 'medium', reason: 'No-show 2× this month.' },
    ],
    valueCreatedMonthUsd: 8420,
    hoursSavedMonth: 92,
    nextAction: { label: 'Review tenant escalation', href: '/app/tasks' },
    topEmployee: { name: 'AI Maintenance Triage Agent', impact: '38 tickets resolved this week without your team touching them.' },
    lifeSignals: [
      {
        agentSlug: 'maintenance-triage',
        agentName: 'AI Maintenance Triage Agent',
        presence: 'working',
        currentlyWorkingOn: 'Triaging burst pipe report at 142 Elm',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 2,
        collaborators: ['AI Vendor Dispatch', 'AI Owner Updates'],
        escalation: { title: 'Tenant complaint at 142 Elm escalated', severity: 'high' },
        memoryUsed: { source: 'Obsidian', snippet: 'Any vendor quote > $400 → owner ping with photos before dispatch.' },
        skillsActive: ['priority-triage', 'photo-evidence', 'tenant-comms'],
        activeWorkflow: 'Emergency Response',
        recentWin: '38 tickets resolved this week without your team touching them',
        currentBlocker: null,
      },
      {
        agentSlug: 'vendor-dispatch',
        agentName: 'AI Vendor Dispatch',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'Quote $620 for water cleanup — held for owner ping',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 5,
        collaborators: ['AI Maintenance Triage Agent', 'AI Owner Updates'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Q1 Doctrine: vendor quote > $400 requires owner photos approval.' },
        skillsActive: ['vendor-routing', 'cost-validation'],
        activeWorkflow: 'Vendor Dispatch',
        recentWin: 'Auto-dispatched 4 maintenance tickets this morning',
        currentBlocker: 'Awaiting owner photo approval for 142 Elm cleanup',
      },
      {
        agentSlug: 'owner-updates',
        agentName: 'AI Owner Updates',
        presence: 'working',
        currentlyWorkingOn: 'Composing monthly owner statements for 14 properties',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 4,
        collaborators: [],
        escalation: null,
        memoryUsed: { source: 'Notion', snippet: 'Owner copy: plain-spoken, warm, never legalese.' },
        skillsActive: ['statement-generation', 'photo-attach'],
        activeWorkflow: 'Monthly Owner Update',
        recentWin: 'Caught a late rent payment before it cascaded — $280 recovered',
        currentBlocker: null,
      },
      {
        agentSlug: 'leasing-assistant',
        agentName: 'AI Leasing Assistant',
        presence: 'idle',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 8,
        collaborators: [],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['tour-scheduling', 'application-review'],
        activeWorkflow: null,
        recentWin: 'Booked 6 tours overnight',
        currentBlocker: null,
      },
    ],
  },
  gc: {
    briefingHeadline: 'Two bids signed overnight. One conflict needs you.',
    dailyWins: [
      { title: 'Awarded Madison St rebuild', impact: '$48k contract', valueUsd: 4800 },
      { title: 'Closed Highland Ave punch list', impact: 'Final payment unlocked', valueUsd: 1200 },
      { title: 'Built bid for Edgewater kitchen', impact: '6 hours saved', valueUsd: 210 },
    ],
    attentionItems: [
      { title: 'Edgewater bid: change-order conflict', severity: 'high', reason: '$4.2k scope overlap between two subs.' },
    ],
    valueCreatedMonthUsd: 17_200,
    hoursSavedMonth: 64,
    nextAction: { label: 'Resolve change-order conflict', href: '/app/tasks' },
    topEmployee: { name: 'AI Bid Estimator', impact: '11 estimates this week — your team would have done 4.' },
    lifeSignals: [
      {
        agentSlug: 'bid-estimator',
        agentName: 'AI Bid Estimator',
        presence: 'working',
        currentlyWorkingOn: 'Building takeoff for Glenwood remodel',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 4,
        collaborators: ['AI Sub Coordinator', 'AI Schedule Planner'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Bid doctrine: never bid under 12% gross margin. Flag soft scopes.' },
        skillsActive: ['takeoff', 'unit-pricing', 'bid-formatting'],
        activeWorkflow: 'Active Bids',
        recentWin: 'Awarded Madison St — $48k contract',
        currentBlocker: null,
      },
      {
        agentSlug: 'sub-coordinator',
        agentName: 'AI Sub Coordinator',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'Edgewater change-order conflict — held for operator',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 6,
        collaborators: ['AI Bid Estimator'],
        escalation: { title: 'Edgewater bid: change-order conflict', severity: 'high' },
        memoryUsed: { source: 'Notion', snippet: 'Two subs scoped the same demo line; need an owner.' },
        skillsActive: ['sub-routing', 'change-order-tracking'],
        activeWorkflow: 'Subcontractor Mesh',
        recentWin: 'Resolved 4 sub conflicts last week before they escalated',
        currentBlocker: 'Two subs claiming the same scope on Edgewater',
      },
      {
        agentSlug: 'schedule-planner',
        agentName: 'AI Schedule Planner',
        presence: 'working',
        currentlyWorkingOn: 'Resequencing Highland Ave punch list to clear final draw',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 5,
        collaborators: ['AI Sub Coordinator'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Punch list rule: photo + GC signoff before draw.' },
        skillsActive: ['punch-list', 'critical-path', 'weather-routing'],
        activeWorkflow: 'Active Jobs',
        recentWin: 'Closed Highland Ave punch list — final payment unlocked',
        currentBlocker: null,
      },
      {
        agentSlug: 'permit-tracker',
        agentName: 'AI Permit Tracker',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 9,
        collaborators: ['AI Schedule Planner'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['permit-status', 'inspector-followup'],
        activeWorkflow: null,
        recentWin: 'Pulled 9 permits this month with zero delays',
        currentBlocker: null,
      },
    ],
  },
  'home-services': {
    briefingHeadline: 'Booked 17 calls overnight. One emergency.',
    dailyWins: [
      { title: 'Booked 17 service calls', impact: '$12k pipeline', valueUsd: 1200 },
      { title: 'Recovered 4 abandoned quotes', impact: '$3.1k recovered', valueUsd: 3100 },
      { title: 'Sent 23 post-service follow-ups', impact: '8 reviews coming', valueUsd: 400 },
    ],
    attentionItems: [
      { title: 'Gas leak reported — no tech in 5-mile radius', severity: 'high', reason: 'AI Dispatcher escalated. Manual override required.' },
    ],
    valueCreatedMonthUsd: 14_300,
    hoursSavedMonth: 88,
    nextAction: { label: 'Resolve emergency dispatch', href: '/app/tasks' },
    topEmployee: { name: 'AI Intake Receptionist', impact: '116 calls answered this month. Zero missed.' },
    lifeSignals: [
      {
        agentSlug: 'intake-receptionist',
        agentName: 'AI Intake Receptionist',
        presence: 'working',
        currentlyWorkingOn: 'Triaging 8 inbound calls — 1 emergency flagged',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 1,
        collaborators: ['AI Dispatcher', 'AI Quote Recovery'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Triage rule: gas/water/electrical = page operator immediately.' },
        skillsActive: ['call-triage', 'sms-confirm', 'after-hours-coverage'],
        activeWorkflow: 'Inbound Calls',
        recentWin: '116 calls answered this month — zero missed',
        currentBlocker: null,
      },
      {
        agentSlug: 'dispatcher',
        agentName: 'AI Dispatcher',
        presence: 'needs-attention',
        currentlyWorkingOn: 'Searching for tech in 5-mile radius for gas leak',
        confidence: 'low',
        workloadPressure: 'heavy',
        responseSpeedMin: 2,
        collaborators: ['AI Intake Receptionist'],
        escalation: { title: 'Gas leak reported — no tech in 5-mile radius', severity: 'high' },
        memoryUsed: { source: 'Notion', snippet: 'Emergency SOP: page nearest tech; if none, call operator.' },
        skillsActive: ['tech-routing', 'eta-prediction'],
        activeWorkflow: 'Live Dispatch',
        recentWin: 'Rerouted 14 jobs around the storm last Tuesday',
        currentBlocker: 'No qualified tech available for emergency',
      },
      {
        agentSlug: 'quote-recovery',
        agentName: 'AI Quote Recovery',
        presence: 'working',
        currentlyWorkingOn: 'Re-engaging 12 stale quotes from last month',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 4,
        collaborators: ['AI Intake Receptionist'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Cadence: T+24h text → T+72h call → T+7d email.' },
        skillsActive: ['quote-recovery', 'sms-outbound', 'price-explain'],
        activeWorkflow: 'Quote Pipeline',
        recentWin: 'Recovered 4 abandoned quotes — $3.1k pipeline reinstated',
        currentBlocker: null,
      },
      {
        agentSlug: 'review-collector',
        agentName: 'AI Review Collector',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 10,
        collaborators: [],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['review-request', 'sentiment-routing'],
        activeWorkflow: null,
        recentWin: '8 five-star reviews booked this week',
        currentBlocker: null,
      },
    ],
  },
  'ai-agency': {
    briefingHeadline: 'Client Alpha had a banner week.',
    dailyWins: [
      { title: 'Delivered ROI deck to Client Alpha', impact: '47h saved · $4.1k labor value', valueUsd: 4100 },
      { title: 'Switched Client Bravo routes to gemini-flash', impact: '$320/mo savings', valueUsd: 320 },
      { title: 'Onboarded Client Charlie', impact: 'New MRR online', valueUsd: 1800 },
    ],
    attentionItems: [
      { title: 'Client Bravo: quality score dipped 14%', severity: 'medium', reason: '3 sessions flagged for human review.' },
    ],
    valueCreatedMonthUsd: 22_400,
    hoursSavedMonth: 142,
    nextAction: { label: 'Review flagged sessions', href: '/app/security-audit' },
    topEmployee: { name: 'AI Workforce Manager', impact: 'Coordinated 3 client onboardings this week.' },
    lifeSignals: [
      {
        agentSlug: 'workforce-manager',
        agentName: 'AI Workforce Manager',
        presence: 'working',
        currentlyWorkingOn: 'Coordinating Client Charlie onboarding kickoff',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 3,
        collaborators: ['AI Client Success', 'AI Skills Operator'],
        escalation: null,
        memoryUsed: { source: 'Notion', snippet: 'New-client kickoff: workspace + 3 employees + 6 skills, live in 24h.' },
        skillsActive: ['client-routing', 'capacity-planning', 'sla-monitor'],
        activeWorkflow: 'New Client Activation',
        recentWin: '3 client onboardings completed this week — all on schedule',
        currentBlocker: null,
      },
      {
        agentSlug: 'client-success',
        agentName: 'AI Client Success',
        presence: 'working',
        currentlyWorkingOn: 'Drafting QBR deck for Client Alpha',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 5,
        collaborators: ['AI Workforce Manager'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'QBR doctrine: lead with hours saved, never with model usage.' },
        skillsActive: ['qbr-deck', 'roi-narrative', 'meeting-notes'],
        activeWorkflow: 'Quarterly Business Review',
        recentWin: 'Delivered ROI deck — Client Alpha renewed at +18% ARR',
        currentBlocker: null,
      },
      {
        agentSlug: 'skills-operator',
        agentName: 'AI Skills Operator',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'Routing Client Bravo to gemini-flash — held for margin check',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 6,
        collaborators: ['AI Workforce Manager'],
        escalation: { title: 'Client Bravo: quality score dipped 14%', severity: 'medium' },
        memoryUsed: { source: 'Obsidian', snippet: 'Cost-routing rule: never sacrifice >5% quality for cost savings.' },
        skillsActive: ['model-routing', 'cost-arbitrage', 'quality-monitor'],
        activeWorkflow: 'Margin Optimization',
        recentWin: 'Switched Client Bravo routes — $320/mo savings logged',
        currentBlocker: 'Awaiting operator sign-off on margin tradeoff',
      },
      {
        agentSlug: 'utilization-watch',
        agentName: 'AI Utilization Watch',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 11,
        collaborators: ['AI Workforce Manager'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['utilization-tracking', 'margin-alert'],
        activeWorkflow: null,
        recentWin: 'Caught a low-margin client before renewal — repriced',
        currentBlocker: null,
      },
    ],
  },
  'real-estate': {
    briefingHeadline: '18 Westwood under contract. Two listings need pricing strategy.',
    dailyWins: [
      { title: '18 Westwood: offer accepted', impact: '$615k sale price', valueUsd: 18_450 },
      { title: 'Qualified 12 inbound buyer leads', impact: '4 hot, 8 nurture', valueUsd: 1200 },
      { title: 'Sent 31 post-close nurture emails', impact: '7 referrals pending', valueUsd: 800 },
    ],
    attentionItems: [
      { title: 'Counter-offer terms unclear on 18 Westwood', severity: 'high', reason: 'AI Transaction Coordinator wants your call before responding.' },
    ],
    valueCreatedMonthUsd: 28_600,
    hoursSavedMonth: 71,
    nextAction: { label: 'Approve counter-offer response', href: '/app/tasks' },
    topEmployee: { name: 'AI Lead Capture Assistant', impact: '12 leads qualified · zero touched by a human first.' },
    lifeSignals: [
      {
        agentSlug: 'lead-capture',
        agentName: 'AI Lead Capture Assistant',
        presence: 'working',
        currentlyWorkingOn: 'Qualifying 3 inbound buyers from Zillow',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 2,
        collaborators: ['AI Transaction Coordinator'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Qualification rubric: pre-approval, timeline, area, agent status.' },
        skillsActive: ['lead-qualifying', 'sms-reply', 'showing-scheduling'],
        activeWorkflow: 'Buyer Pipeline',
        recentWin: '12 leads qualified — zero touched by a human first',
        currentBlocker: null,
      },
      {
        agentSlug: 'transaction-coordinator',
        agentName: 'AI Transaction Coordinator',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: '18 Westwood counter-offer terms — held for agent',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 8,
        collaborators: ['AI Lead Capture', 'AI Listing Specialist'],
        escalation: { title: '18 Westwood counter-offer terms unclear', severity: 'high' },
        memoryUsed: { source: 'Notion', snippet: 'TC playbook: never sign counter terms without agent review.' },
        skillsActive: ['contract-tracking', 'deadline-alerts', 'inspection-coord'],
        activeWorkflow: 'Active Contracts',
        recentWin: 'Closed 4 transactions this month — zero missed deadlines',
        currentBlocker: 'Awaiting agent decision on counter-offer concessions',
      },
      {
        agentSlug: 'listing-specialist',
        agentName: 'AI Listing Specialist',
        presence: 'working',
        currentlyWorkingOn: 'Drafting listing description for 1144 Maple Ave',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 6,
        collaborators: ['AI Transaction Coordinator'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Listing voice: 50 words of lifestyle, 50 words of facts, never both blurred.' },
        skillsActive: ['listing-copy', 'comp-analysis', 'mls-publish'],
        activeWorkflow: 'New Listings',
        recentWin: 'Published 6 listings this week — 4 had offers within 72h',
        currentBlocker: null,
      },
      {
        agentSlug: 'nurture-bot',
        agentName: 'AI Nurture Concierge',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 12,
        collaborators: ['AI Lead Capture'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['post-close-nurture', 'referral-asks', 'birthday-touch'],
        activeWorkflow: null,
        recentWin: '7 referrals pending from post-close nurture',
        currentBlocker: null,
      },
    ],
  },
  mortgage: {
    briefingHeadline: 'Six loans funded this month. One appraisal came in low.',
    dailyWins: [
      { title: 'Funded 6 loans this month', impact: '$1.8M closed volume', valueUsd: 18_000 },
      { title: 'Sent rate quotes to 22 borrowers', impact: '3 ready to sign', valueUsd: 900 },
      { title: 'Cleared underwriting for #4377', impact: 'On track for Friday close', valueUsd: 600 },
    ],
    attentionItems: [
      { title: 'Borrower #4421: appraisal came in $14k under contract', severity: 'high', reason: 'Loan officer needs to call before automated email goes out.' },
    ],
    valueCreatedMonthUsd: 24_900,
    hoursSavedMonth: 96,
    nextAction: { label: 'Call borrower #4421', href: '/app/tasks' },
    topEmployee: { name: 'AI Doc Collection Assistant', impact: '94% of borrowers have all docs in within 7 days.' },
    lifeSignals: [
      {
        agentSlug: 'doc-collection',
        agentName: 'AI Doc Collection Assistant',
        presence: 'working',
        currentlyWorkingOn: 'Chasing missing pay stubs from borrower #4439',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 3,
        collaborators: ['AI Loan Coordinator', 'AI Rate Quote Bot'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Doc SOP: T+0 portal, T+48h SMS, T+5d phone. Never email twice in a row.' },
        skillsActive: ['document-chase', 'sms-outbound', 'borrower-portal'],
        activeWorkflow: 'Doc Collection Pipeline',
        recentWin: '94% of borrowers have all docs in within 7 days',
        currentBlocker: null,
      },
      {
        agentSlug: 'loan-coordinator',
        agentName: 'AI Loan Coordinator',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'Borrower #4421 — appraisal $14k low; held for loan officer',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 7,
        collaborators: ['AI Doc Collection', 'AI Underwriting Watch'],
        escalation: { title: 'Borrower #4421 appraisal $14k under contract', severity: 'high' },
        memoryUsed: { source: 'Notion', snippet: 'Low-appraisal SOP: never auto-email; LO calls borrower first.' },
        skillsActive: ['pipeline-tracking', 'milestone-alerts'],
        activeWorkflow: 'Active Pipelines',
        recentWin: '6 loans funded this month — $1.8M closed volume',
        currentBlocker: 'Awaiting LO decision on low-appraisal handling',
      },
      {
        agentSlug: 'rate-quote-bot',
        agentName: 'AI Rate Quote Bot',
        presence: 'working',
        currentlyWorkingOn: 'Refreshing rate sheets for 14 prospects',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 4,
        collaborators: ['AI Doc Collection'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'Rate doctrine: always show APR + monthly payment + 5-yr cost.' },
        skillsActive: ['rate-quote', 'sms-outbound', 'pre-qual-routing'],
        activeWorkflow: 'Rate Quote Pipeline',
        recentWin: '22 rate quotes sent — 3 borrowers ready to sign',
        currentBlocker: null,
      },
      {
        agentSlug: 'underwriting-watch',
        agentName: 'AI Underwriting Watch',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 11,
        collaborators: ['AI Loan Coordinator'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['condition-tracker', 'compliance-watch'],
        activeWorkflow: null,
        recentWin: 'Cleared 7 underwriting condition lists ahead of schedule',
        currentBlocker: null,
      },
    ],
  },
  cpa: {
    briefingHeadline: 'Tax season pressure is dropping. One reconciliation needs you.',
    dailyWins: [
      { title: 'Filed extensions for 9 clients', impact: '12 hours saved', valueUsd: 540 },
      { title: 'Closed monthly books for 11 clients', impact: 'On time for the first quarter ever', valueUsd: 2400 },
      { title: 'Sent payroll reminders to 24 clients', impact: '0 late filings', valueUsd: 800 },
    ],
    attentionItems: [
      { title: 'Client #88 — 1099 reconciliation discrepancy ($3,200)', severity: 'high', reason: 'AI flagged. Needs partner review before filing.' },
    ],
    valueCreatedMonthUsd: 11_900,
    hoursSavedMonth: 124,
    nextAction: { label: 'Review #88 reconciliation', href: '/app/tasks' },
    topEmployee: { name: 'AI Tax Document Organizer', impact: 'Chased 47 missing W-2s this week with zero staff time.' },
    lifeSignals: [
      {
        agentSlug: 'tax-doc-organizer',
        agentName: 'AI Tax Document Organizer',
        presence: 'working',
        currentlyWorkingOn: 'Chasing missing W-2 from client #211',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 3,
        collaborators: ['AI Senior CPA', 'AI Bookkeeper'],
        escalation: null,
        memoryUsed: { source: 'Obsidian', snippet: 'SOP — outreach cadence: T+0 → T+72h → T+7d phone.' },
        skillsActive: ['document-chase', 'sms-outbound', 'email-followup'],
        activeWorkflow: 'Q1 W-2 Collection',
        recentWin: 'Closed W-2 collection for 47 clients this week',
        currentBlocker: null,
      },
      {
        agentSlug: 'senior-cpa',
        agentName: 'AI Senior CPA',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'Client #88 reconciliation — held for partner review',
        confidence: 'medium',
        workloadPressure: 'balanced',
        responseSpeedMin: 7,
        collaborators: ['AI Tax Document Organizer'],
        escalation: { title: 'Client #88 reconciliation discrepancy ($3,200)', severity: 'high' },
        memoryUsed: { source: 'Obsidian', snippet: 'Q1 Doctrine: never file where 1099 totals do not reconcile. Escalate to operator with delta first.' },
        skillsActive: ['reconciliation', 'partner-escalation'],
        activeWorkflow: 'Q1 Filing Pipeline',
        recentWin: 'Closed monthly books for 11 clients ahead of schedule',
        currentBlocker: 'Awaiting partner sign-off on client #88',
      },
      {
        agentSlug: 'bookkeeper',
        agentName: 'AI Bookkeeper',
        presence: 'working',
        currentlyWorkingOn: 'Posting March transactions for 6 clients',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 2,
        collaborators: ['AI Senior CPA'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['bank-feed-sync', 'category-mapping'],
        activeWorkflow: 'Daily Close',
        recentWin: 'Posted 312 transactions today, 0 manual review needed',
        currentBlocker: null,
      },
      {
        agentSlug: 'client-success',
        agentName: 'AI Client Success Manager',
        presence: 'idle',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 9,
        collaborators: ['AI Tax Document Organizer'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['client-survey'],
        activeWorkflow: null,
        recentWin: 'Sent Q1 NPS to 38 clients — 9.1 avg',
        currentBlocker: null,
      },
    ],
  },
  'marketing-agency': {
    briefingHeadline: 'Orion campaign live. One ad blocked.',
    dailyWins: [
      { title: 'Launched Orion paid-social campaign', impact: '12 ad variants live', valueUsd: 1800 },
      { title: 'Delivered Q1 reports for 8 clients', impact: '34 hours saved', valueUsd: 1400 },
      { title: 'Repurposed 4 posts into 28 social pieces', impact: 'Content shelf full', valueUsd: 600 },
    ],
    attentionItems: [
      { title: 'Client Orion ad blocked by platform policy', severity: 'medium', reason: 'Needs creative revision before relaunch.' },
    ],
    valueCreatedMonthUsd: 18_700,
    hoursSavedMonth: 108,
    nextAction: { label: 'Revise blocked creative', href: '/app/tasks' },
    topEmployee: { name: 'AI Content Strategist', impact: 'Published 28 client pieces this week.' },
    lifeSignals: [
      {
        agentSlug: 'campaign-operator',
        agentName: 'AI Campaign Operator',
        presence: 'working',
        currentlyWorkingOn: 'Drafting brief for Orion Q2 launch — pulling from brand book',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 4,
        collaborators: ['AI Content Calendar Manager', 'AI Reporting Analyst'],
        escalation: { title: 'Orion ad rejected by Meta — creative review needed', severity: 'medium' },
        memoryUsed: { source: 'Notion', snippet: 'Orion brand book: never use stock people. Always real client testimonials.' },
        skillsActive: ['campaign-brief', 'creative-routing', 'brand-compliance'],
        activeWorkflow: 'Q2 Campaign Launch',
        recentWin: 'Launched 12 ad variants for Orion in 6 hours (was 2 days)',
        currentBlocker: 'Awaiting designer revision on flagged creative',
      },
      {
        agentSlug: 'content-calendar',
        agentName: 'AI Content Calendar Manager',
        presence: 'working',
        currentlyWorkingOn: 'Filling content gaps for 8 clients · 30-day runway',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 5,
        collaborators: ['AI Campaign Operator'],
        escalation: null,
        memoryUsed: { source: 'Pinecone', snippet: 'Top performers Q1: how-to posts (Acme), testimonials (Orion), behind-the-scenes (Helio).' },
        skillsActive: ['calendar-fill', 'hook-library', 'asset-tracking'],
        activeWorkflow: 'Weekly Editorial Plan',
        recentWin: '4 client calendars full 30 days out — no gaps',
        currentBlocker: null,
      },
      {
        agentSlug: 'reporting-analyst',
        agentName: 'AI Reporting Analyst',
        presence: 'working',
        currentlyWorkingOn: 'Drafting weekly ROI report for Helio — pulling Meta + Google + LinkedIn',
        confidence: 'high',
        workloadPressure: 'heavy',
        responseSpeedMin: 7,
        collaborators: ['AI Client Success Assistant'],
        escalation: null,
        memoryUsed: { source: 'Custom DB', snippet: 'Helio KPI set: CAC, ROAS, MQL→SQL, no vanity metrics.' },
        skillsActive: ['ad-platform-read', 'roi-roll-up', 'plain-language-summary'],
        activeWorkflow: 'Weekly Client Reports',
        recentWin: '8 client reports drafted Friday in 18min (was 4h/client)',
        currentBlocker: null,
      },
      {
        agentSlug: 'lead-followup',
        agentName: 'AI Lead Follow-Up Agent',
        presence: 'online',
        currentlyWorkingOn: 'Running adaptive cadence on 142 inbound leads',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 2,
        collaborators: [],
        escalation: null,
        memoryUsed: { source: 'CRM', snippet: 'Offer ladder: free audit → strategy call → 90-day pilot.' },
        skillsActive: ['cadence-run', 'lead-scoring', 'handoff-to-am'],
        activeWorkflow: 'Inbound Lead Touch',
        recentWin: '+24% inbound conversion vs. last quarter',
        currentBlocker: null,
      },
    ],
  },
  'law-firm': {
    briefingHeadline: 'Four intakes overnight. One may be a conflict.',
    dailyWins: [
      { title: 'Closed 4 client intakes', impact: 'Consults booked', valueUsd: 1200 },
      { title: 'Sent matter updates to 14 clients', impact: 'Zero client chase emails today', valueUsd: 700 },
      { title: 'Cleared 3 document collections', impact: 'Filing-ready', valueUsd: 800 },
    ],
    attentionItems: [
      { title: 'New intake: potential conflict of interest detected', severity: 'high', reason: 'AI flagged via similar-matter check. Attorney must clear before consult.' },
    ],
    valueCreatedMonthUsd: 14_200,
    hoursSavedMonth: 88,
    nextAction: { label: 'Clear conflict check', href: '/app/tasks' },
    topEmployee: { name: 'AI Case Summary Assistant', impact: 'Drafted 22 matter summaries this week.' },
    lifeSignals: [
      {
        agentSlug: 'intake-assistant',
        agentName: 'AI Intake Assistant',
        presence: 'waiting-for-approval',
        currentlyWorkingOn: 'New intake: Henderson v. Westview — conflict-check held',
        confidence: 'medium',
        workloadPressure: 'heavy',
        responseSpeedMin: 4,
        collaborators: ['AI Conflict Check Agent', 'AI Case Summary Assistant'],
        escalation: { title: 'Potential conflict of interest — attorney sign-off required', severity: 'high' },
        memoryUsed: { source: 'Notion', snippet: 'Intake SOP: run conflict check BEFORE first consult is scheduled.' },
        skillsActive: ['intake-form', 'conflict-search'],
        activeWorkflow: 'New Client Intake',
        recentWin: 'Closed 4 intakes overnight — 100% packet completeness',
        currentBlocker: 'Awaiting attorney clearance on Henderson intake',
      },
      {
        agentSlug: 'case-summary',
        agentName: 'AI Case Summary Assistant',
        presence: 'working',
        currentlyWorkingOn: 'Drafting matter summary for Roberts complaint',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 6,
        collaborators: ['AI Intake Assistant'],
        escalation: null,
        memoryUsed: { source: 'Pinecone', snippet: 'Similar matter recall: Walters complaint (closed 2024-08).' },
        skillsActive: ['document-summary', 'matter-tagging'],
        activeWorkflow: 'Matter Brief Generation',
        recentWin: 'Drafted 22 matter summaries this week',
        currentBlocker: null,
      },
      {
        agentSlug: 'client-comms',
        agentName: 'AI Client Communications',
        presence: 'working',
        currentlyWorkingOn: 'Sending matter updates to 14 active clients',
        confidence: 'high',
        workloadPressure: 'balanced',
        responseSpeedMin: 3,
        collaborators: [],
        escalation: null,
        memoryUsed: { source: 'Notion', snippet: 'Tone: firm, specific, never legalese.' },
        skillsActive: ['matter-update-email', 'scheduling'],
        activeWorkflow: 'Weekly Client Touch',
        recentWin: 'Zero client chase emails today',
        currentBlocker: null,
      },
      {
        agentSlug: 'compliance-watch',
        agentName: 'AI Compliance Watch',
        presence: 'online',
        currentlyWorkingOn: null,
        confidence: 'high',
        workloadPressure: 'light',
        responseSpeedMin: 12,
        collaborators: ['AI Intake Assistant'],
        escalation: null,
        memoryUsed: null,
        skillsActive: ['advertising-rules', 'fee-agreement-review'],
        activeWorkflow: null,
        recentWin: 'Flagged 1 advertising-rule risk pre-publication',
        currentBlocker: null,
      },
    ],
  },
}

export function getDemoNarrative(templateId: string): DemoNarrative | null {
  const tpl = BUSINESS_TEMPLATES.find((t) => t.id === templateId)
  if (!tpl) return null
  const n = NARRATIVES[templateId]
  if (!n) return null
  return { template: tpl, ...n }
}

export const DEMO_TEMPLATE_IDS = Object.keys(NARRATIVES)
