/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceOsRouteImport } from './routes/workforce-os'
import { Route as WacrmRouteImport } from './routes/wacrm'
import { Route as VideoStudioRouteImport } from './routes/video-studio'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as TriadRouteImport } from './routes/triad'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SearchChatsRouteImport } from './routes/search-chats'
import { Route as RuntimeRegistryRouteImport } from './routes/runtime-registry'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProductionUnlockRouteImport } from './routes/production-unlock'
import { Route as PineconeRouteImport } from './routes/pinecone'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as OrgChartRouteImport } from './routes/org-chart'
import { Route as NotionRouteImport } from './routes/notion'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as MinimaxRouteImport } from './routes/minimax'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MaestroRouteImport } from './routes/maestro'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KanbanGalleryRouteImport } from './routes/kanban-gallery'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ImportedSkillsRouteImport } from './routes/imported-skills'
import { Route as HyperframesRouteImport } from './routes/hyperframes'
import { Route as HypereditRouteImport } from './routes/hyperedit'
import { Route as HiggsfieldRouteImport } from './routes/higgsfield'
import { Route as HermesMcpLoopRouteImport } from './routes/hermes-mcp-loop'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GraphifyRouteImport } from './routes/graphify'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FlightDeckRouteImport } from './routes/flight-deck'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CliRouteImport } from './routes/cli'
import { Route as ClaudeclawRouteImport } from './routes/claudeclaw'
import { Route as BrowserRouteImport } from './routes/browser'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as WorkspacesIdRouteImport } from './routes/workspaces.$id'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as ClaudeclawStudioRouteImport } from './routes/claudeclaw.studio'
import { Route as AppActivateRouteImport } from './routes/app.activate'
import { Route as AgentsSlimCharlesRouteImport } from './routes/agents.slim-charles'
import { Route as AgentsRufloRouteImport } from './routes/agents.ruflo'
import { Route as AgentsPiRuntimeRouteImport } from './routes/agents.pi-runtime'
import { Route as AgentsOpenclawRouteImport } from './routes/agents.openclaw'
import { Route as AgentsNotebooklmRouteImport } from './routes/agents.notebooklm'
import { Route as AgentsHermesMcpRouteImport } from './routes/agents.hermes-mcp'
import { Route as AgentsHermesRouteImport } from './routes/agents.hermes'
import { Route as AgentsGeminiRouteImport } from './routes/agents.gemini'
import { Route as AgentsFreeClaudeRouteImport } from './routes/agents.free-claude'
import { Route as AgentsCodexRouteImport } from './routes/agents.codex'
import { Route as AgentsClaudeCodeStudioRouteImport } from './routes/agents.claude-code-studio'
import { Route as AgentsClaudeCodeRouteImport } from './routes/agents.claude-code'
import { Route as AgentsAntigravityRouteImport } from './routes/agents.antigravity'
import { Route as AgentsOpenclawStudioRouteImport } from './routes/agents.openclaw.studio'
import { Route as AgentsHermesWorkspaceRouteImport } from './routes/agents.hermes.workspace'
import { Route as AgentsHermesStudioRouteImport } from './routes/agents.hermes.studio'
import { Route as AgentsHermesGoalRouteImport } from './routes/agents.hermes.goal'
import { Route as AgentsHermesControlRouteImport } from './routes/agents.hermes.control'
import { Route as AgentsGeminiStudioRouteImport } from './routes/agents.gemini.studio'
import { Route as AgentsFreeClaudeStudioRouteImport } from './routes/agents.free-claude.studio'

const WorkforceOsRoute = WorkforceOsRouteImport.update({
  id: '/workforce-os',
  path: '/workforce-os',
  getParentRoute: () => rootRouteImport,
} as any)
const WacrmRoute = WacrmRouteImport.update({
  id: '/wacrm',
  path: '/wacrm',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoStudioRoute = VideoStudioRouteImport.update({
  id: '/video-studio',
  path: '/video-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const TriadRoute = TriadRouteImport.update({
  id: '/triad',
  path: '/triad',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchChatsRoute = SearchChatsRouteImport.update({
  id: '/search-chats',
  path: '/search-chats',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRegistryRoute = RuntimeRegistryRouteImport.update({
  id: '/runtime-registry',
  path: '/runtime-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionUnlockRoute = ProductionUnlockRouteImport.update({
  id: '/production-unlock',
  path: '/production-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const PineconeRoute = PineconeRouteImport.update({
  id: '/pinecone',
  path: '/pinecone',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgChartRoute = OrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const NotionRoute = NotionRouteImport.update({
  id: '/notion',
  path: '/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimaxRoute = MinimaxRouteImport.update({
  id: '/minimax',
  path: '/minimax',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MaestroRoute = MaestroRouteImport.update({
  id: '/maestro',
  path: '/maestro',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanGalleryRoute = KanbanGalleryRouteImport.update({
  id: '/kanban-gallery',
  path: '/kanban-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportedSkillsRoute = ImportedSkillsRouteImport.update({
  id: '/imported-skills',
  path: '/imported-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperframesRoute = HyperframesRouteImport.update({
  id: '/hyperframes',
  path: '/hyperframes',
  getParentRoute: () => rootRouteImport,
} as any)
const HypereditRoute = HypereditRouteImport.update({
  id: '/hyperedit',
  path: '/hyperedit',
  getParentRoute: () => rootRouteImport,
} as any)
const HiggsfieldRoute = HiggsfieldRouteImport.update({
  id: '/higgsfield',
  path: '/higgsfield',
  getParentRoute: () => rootRouteImport,
} as any)
const HermesMcpLoopRoute = HermesMcpLoopRouteImport.update({
  id: '/hermes-mcp-loop',
  path: '/hermes-mcp-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphifyRoute = GraphifyRouteImport.update({
  id: '/graphify',
  path: '/graphify',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightDeckRoute = FlightDeckRouteImport.update({
  id: '/flight-deck',
  path: '/flight-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeclawRoute = ClaudeclawRouteImport.update({
  id: '/claudeclaw',
  path: '/claudeclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserRoute = BrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIdRoute = WorkspacesIdRouteImport.update({
  id: '/workspaces/$id',
  path: '/workspaces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const ClaudeclawStudioRoute = ClaudeclawStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => ClaudeclawRoute,
} as any)
const AppActivateRoute = AppActivateRouteImport.update({
  id: '/app/activate',
  path: '/app/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlimCharlesRoute = AgentsSlimCharlesRouteImport.update({
  id: '/agents/slim-charles',
  path: '/agents/slim-charles',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRufloRoute = AgentsRufloRouteImport.update({
  id: '/agents/ruflo',
  path: '/agents/ruflo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsPiRuntimeRoute = AgentsPiRuntimeRouteImport.update({
  id: '/agents/pi-runtime',
  path: '/agents/pi-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOpenclawRoute = AgentsOpenclawRouteImport.update({
  id: '/agents/openclaw',
  path: '/agents/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNotebooklmRoute = AgentsNotebooklmRouteImport.update({
  id: '/agents/notebooklm',
  path: '/agents/notebooklm',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHermesMcpRoute = AgentsHermesMcpRouteImport.update({
  id: '/agents/hermes-mcp',
  path: '/agents/hermes-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsHermesRoute = AgentsHermesRouteImport.update({
  id: '/agents/hermes',
  path: '/agents/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsGeminiRoute = AgentsGeminiRouteImport.update({
  id: '/agents/gemini',
  path: '/agents/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsFreeClaudeRoute = AgentsFreeClaudeRouteImport.update({
  id: '/agents/free-claude',
  path: '/agents/free-claude',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsCodexRoute = AgentsCodexRouteImport.update({
  id: '/agents/codex',
  path: '/agents/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClaudeCodeStudioRoute = AgentsClaudeCodeStudioRouteImport.update({
  id: '/agents/claude-code-studio',
  path: '/agents/claude-code-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsClaudeCodeRoute = AgentsClaudeCodeRouteImport.update({
  id: '/agents/claude-code',
  path: '/agents/claude-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAntigravityRoute = AgentsAntigravityRouteImport.update({
  id: '/agents/antigravity',
  path: '/agents/antigravity',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOpenclawStudioRoute = AgentsOpenclawStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AgentsOpenclawRoute,
} as any)
const AgentsHermesWorkspaceRoute = AgentsHermesWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AgentsHermesRoute,
} as any)
const AgentsHermesStudioRoute = AgentsHermesStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AgentsHermesRoute,
} as any)
const AgentsHermesGoalRoute = AgentsHermesGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => AgentsHermesRoute,
} as any)
const AgentsHermesControlRoute = AgentsHermesControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AgentsHermesRoute,
} as any)
const AgentsGeminiStudioRoute = AgentsGeminiStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AgentsGeminiRoute,
} as any)
const AgentsFreeClaudeStudioRoute = AgentsFreeClaudeStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AgentsFreeClaudeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/browser': typeof BrowserRoute
  '/claudeclaw': typeof ClaudeclawRouteWithChildren
  '/cli': typeof CliRoute
  '/demo': typeof DemoRoute
  '/documents': typeof DocumentsRoute
  '/flight-deck': typeof FlightDeckRoute
  '/goals': typeof GoalsRoute
  '/graphify': typeof GraphifyRoute
  '/guide': typeof GuideRoute
  '/hermes-mcp-loop': typeof HermesMcpLoopRoute
  '/higgsfield': typeof HiggsfieldRoute
  '/hyperedit': typeof HypereditRoute
  '/hyperframes': typeof HyperframesRoute
  '/imported-skills': typeof ImportedSkillsRoute
  '/journal': typeof JournalRoute
  '/kanban': typeof KanbanRoute
  '/kanban-gallery': typeof KanbanGalleryRoute
  '/library': typeof LibraryRoute
  '/maestro': typeof MaestroRoute
  '/memory': typeof MemoryRoute
  '/minimax': typeof MinimaxRoute
  '/mission-control': typeof MissionControlRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/notion': typeof NotionRoute
  '/org-chart': typeof OrgChartRoute
  '/personas': typeof PersonasRoute
  '/pinecone': typeof PineconeRoute
  '/production-unlock': typeof ProductionUnlockRoute
  '/prompts': typeof PromptsRoute
  '/replay': typeof ReplayRoute
  '/runtime-registry': typeof RuntimeRegistryRoute
  '/search-chats': typeof SearchChatsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/triad': typeof TriadRoute
  '/understand': typeof UnderstandRoute
  '/video-studio': typeof VideoStudioRoute
  '/wacrm': typeof WacrmRoute
  '/workforce-os': typeof WorkforceOsRoute
  '/agents/antigravity': typeof AgentsAntigravityRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/claude-code-studio': typeof AgentsClaudeCodeStudioRoute
  '/agents/codex': typeof AgentsCodexRoute
  '/agents/free-claude': typeof AgentsFreeClaudeRouteWithChildren
  '/agents/gemini': typeof AgentsGeminiRouteWithChildren
  '/agents/hermes': typeof AgentsHermesRouteWithChildren
  '/agents/hermes-mcp': typeof AgentsHermesMcpRoute
  '/agents/notebooklm': typeof AgentsNotebooklmRoute
  '/agents/openclaw': typeof AgentsOpenclawRouteWithChildren
  '/agents/pi-runtime': typeof AgentsPiRuntimeRoute
  '/agents/ruflo': typeof AgentsRufloRoute
  '/agents/slim-charles': typeof AgentsSlimCharlesRoute
  '/app/activate': typeof AppActivateRoute
  '/claudeclaw/studio': typeof ClaudeclawStudioRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/agents/free-claude/studio': typeof AgentsFreeClaudeStudioRoute
  '/agents/gemini/studio': typeof AgentsGeminiStudioRoute
  '/agents/hermes/control': typeof AgentsHermesControlRoute
  '/agents/hermes/goal': typeof AgentsHermesGoalRoute
  '/agents/hermes/studio': typeof AgentsHermesStudioRoute
  '/agents/hermes/workspace': typeof AgentsHermesWorkspaceRoute
  '/agents/openclaw/studio': typeof AgentsOpenclawStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/browser': typeof BrowserRoute
  '/claudeclaw': typeof ClaudeclawRouteWithChildren
  '/cli': typeof CliRoute
  '/demo': typeof DemoRoute
  '/documents': typeof DocumentsRoute
  '/flight-deck': typeof FlightDeckRoute
  '/goals': typeof GoalsRoute
  '/graphify': typeof GraphifyRoute
  '/guide': typeof GuideRoute
  '/hermes-mcp-loop': typeof HermesMcpLoopRoute
  '/higgsfield': typeof HiggsfieldRoute
  '/hyperedit': typeof HypereditRoute
  '/hyperframes': typeof HyperframesRoute
  '/imported-skills': typeof ImportedSkillsRoute
  '/journal': typeof JournalRoute
  '/kanban': typeof KanbanRoute
  '/kanban-gallery': typeof KanbanGalleryRoute
  '/library': typeof LibraryRoute
  '/maestro': typeof MaestroRoute
  '/memory': typeof MemoryRoute
  '/minimax': typeof MinimaxRoute
  '/mission-control': typeof MissionControlRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/notion': typeof NotionRoute
  '/org-chart': typeof OrgChartRoute
  '/personas': typeof PersonasRoute
  '/pinecone': typeof PineconeRoute
  '/production-unlock': typeof ProductionUnlockRoute
  '/prompts': typeof PromptsRoute
  '/replay': typeof ReplayRoute
  '/runtime-registry': typeof RuntimeRegistryRoute
  '/search-chats': typeof SearchChatsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/triad': typeof TriadRoute
  '/understand': typeof UnderstandRoute
  '/video-studio': typeof VideoStudioRoute
  '/wacrm': typeof WacrmRoute
  '/workforce-os': typeof WorkforceOsRoute
  '/agents/antigravity': typeof AgentsAntigravityRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/claude-code-studio': typeof AgentsClaudeCodeStudioRoute
  '/agents/codex': typeof AgentsCodexRoute
  '/agents/free-claude': typeof AgentsFreeClaudeRouteWithChildren
  '/agents/gemini': typeof AgentsGeminiRouteWithChildren
  '/agents/hermes': typeof AgentsHermesRouteWithChildren
  '/agents/hermes-mcp': typeof AgentsHermesMcpRoute
  '/agents/notebooklm': typeof AgentsNotebooklmRoute
  '/agents/openclaw': typeof AgentsOpenclawRouteWithChildren
  '/agents/pi-runtime': typeof AgentsPiRuntimeRoute
  '/agents/ruflo': typeof AgentsRufloRoute
  '/agents/slim-charles': typeof AgentsSlimCharlesRoute
  '/app/activate': typeof AppActivateRoute
  '/claudeclaw/studio': typeof ClaudeclawStudioRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/agents/free-claude/studio': typeof AgentsFreeClaudeStudioRoute
  '/agents/gemini/studio': typeof AgentsGeminiStudioRoute
  '/agents/hermes/control': typeof AgentsHermesControlRoute
  '/agents/hermes/goal': typeof AgentsHermesGoalRoute
  '/agents/hermes/studio': typeof AgentsHermesStudioRoute
  '/agents/hermes/workspace': typeof AgentsHermesWorkspaceRoute
  '/agents/openclaw/studio': typeof AgentsOpenclawStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/browser': typeof BrowserRoute
  '/claudeclaw': typeof ClaudeclawRouteWithChildren
  '/cli': typeof CliRoute
  '/demo': typeof DemoRoute
  '/documents': typeof DocumentsRoute
  '/flight-deck': typeof FlightDeckRoute
  '/goals': typeof GoalsRoute
  '/graphify': typeof GraphifyRoute
  '/guide': typeof GuideRoute
  '/hermes-mcp-loop': typeof HermesMcpLoopRoute
  '/higgsfield': typeof HiggsfieldRoute
  '/hyperedit': typeof HypereditRoute
  '/hyperframes': typeof HyperframesRoute
  '/imported-skills': typeof ImportedSkillsRoute
  '/journal': typeof JournalRoute
  '/kanban': typeof KanbanRoute
  '/kanban-gallery': typeof KanbanGalleryRoute
  '/library': typeof LibraryRoute
  '/maestro': typeof MaestroRoute
  '/memory': typeof MemoryRoute
  '/minimax': typeof MinimaxRoute
  '/mission-control': typeof MissionControlRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/notion': typeof NotionRoute
  '/org-chart': typeof OrgChartRoute
  '/personas': typeof PersonasRoute
  '/pinecone': typeof PineconeRoute
  '/production-unlock': typeof ProductionUnlockRoute
  '/prompts': typeof PromptsRoute
  '/replay': typeof ReplayRoute
  '/runtime-registry': typeof RuntimeRegistryRoute
  '/search-chats': typeof SearchChatsRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRoute
  '/triad': typeof TriadRoute
  '/understand': typeof UnderstandRoute
  '/video-studio': typeof VideoStudioRoute
  '/wacrm': typeof WacrmRoute
  '/workforce-os': typeof WorkforceOsRoute
  '/agents/antigravity': typeof AgentsAntigravityRoute
  '/agents/claude-code': typeof AgentsClaudeCodeRoute
  '/agents/claude-code-studio': typeof AgentsClaudeCodeStudioRoute
  '/agents/codex': typeof AgentsCodexRoute
  '/agents/free-claude': typeof AgentsFreeClaudeRouteWithChildren
  '/agents/gemini': typeof AgentsGeminiRouteWithChildren
  '/agents/hermes': typeof AgentsHermesRouteWithChildren
  '/agents/hermes-mcp': typeof AgentsHermesMcpRoute
  '/agents/notebooklm': typeof AgentsNotebooklmRoute
  '/agents/openclaw': typeof AgentsOpenclawRouteWithChildren
  '/agents/pi-runtime': typeof AgentsPiRuntimeRoute
  '/agents/ruflo': typeof AgentsRufloRoute
  '/agents/slim-charles': typeof AgentsSlimCharlesRoute
  '/app/activate': typeof AppActivateRoute
  '/claudeclaw/studio': typeof ClaudeclawStudioRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/workspaces/$id': typeof WorkspacesIdRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/agents/free-claude/studio': typeof AgentsFreeClaudeStudioRoute
  '/agents/gemini/studio': typeof AgentsGeminiStudioRoute
  '/agents/hermes/control': typeof AgentsHermesControlRoute
  '/agents/hermes/goal': typeof AgentsHermesGoalRoute
  '/agents/hermes/studio': typeof AgentsHermesStudioRoute
  '/agents/hermes/workspace': typeof AgentsHermesWorkspaceRoute
  '/agents/openclaw/studio': typeof AgentsOpenclawStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/approvals'
    | '/browser'
    | '/claudeclaw'
    | '/cli'
    | '/demo'
    | '/documents'
    | '/flight-deck'
    | '/goals'
    | '/graphify'
    | '/guide'
    | '/hermes-mcp-loop'
    | '/higgsfield'
    | '/hyperedit'
    | '/hyperframes'
    | '/imported-skills'
    | '/journal'
    | '/kanban'
    | '/kanban-gallery'
    | '/library'
    | '/maestro'
    | '/memory'
    | '/minimax'
    | '/mission-control'
    | '/notebook'
    | '/notes'
    | '/notion'
    | '/org-chart'
    | '/personas'
    | '/pinecone'
    | '/production-unlock'
    | '/prompts'
    | '/replay'
    | '/runtime-registry'
    | '/search-chats'
    | '/seo'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/studio'
    | '/triad'
    | '/understand'
    | '/video-studio'
    | '/wacrm'
    | '/workforce-os'
    | '/agents/antigravity'
    | '/agents/claude-code'
    | '/agents/claude-code-studio'
    | '/agents/codex'
    | '/agents/free-claude'
    | '/agents/gemini'
    | '/agents/hermes'
    | '/agents/hermes-mcp'
    | '/agents/notebooklm'
    | '/agents/openclaw'
    | '/agents/pi-runtime'
    | '/agents/ruflo'
    | '/agents/slim-charles'
    | '/app/activate'
    | '/claudeclaw/studio'
    | '/settings/api-keys'
    | '/workspaces/$id'
    | '/workspaces/'
    | '/agents/free-claude/studio'
    | '/agents/gemini/studio'
    | '/agents/hermes/control'
    | '/agents/hermes/goal'
    | '/agents/hermes/studio'
    | '/agents/hermes/workspace'
    | '/agents/openclaw/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/approvals'
    | '/browser'
    | '/claudeclaw'
    | '/cli'
    | '/demo'
    | '/documents'
    | '/flight-deck'
    | '/goals'
    | '/graphify'
    | '/guide'
    | '/hermes-mcp-loop'
    | '/higgsfield'
    | '/hyperedit'
    | '/hyperframes'
    | '/imported-skills'
    | '/journal'
    | '/kanban'
    | '/kanban-gallery'
    | '/library'
    | '/maestro'
    | '/memory'
    | '/minimax'
    | '/mission-control'
    | '/notebook'
    | '/notes'
    | '/notion'
    | '/org-chart'
    | '/personas'
    | '/pinecone'
    | '/production-unlock'
    | '/prompts'
    | '/replay'
    | '/runtime-registry'
    | '/search-chats'
    | '/seo'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/studio'
    | '/triad'
    | '/understand'
    | '/video-studio'
    | '/wacrm'
    | '/workforce-os'
    | '/agents/antigravity'
    | '/agents/claude-code'
    | '/agents/claude-code-studio'
    | '/agents/codex'
    | '/agents/free-claude'
    | '/agents/gemini'
    | '/agents/hermes'
    | '/agents/hermes-mcp'
    | '/agents/notebooklm'
    | '/agents/openclaw'
    | '/agents/pi-runtime'
    | '/agents/ruflo'
    | '/agents/slim-charles'
    | '/app/activate'
    | '/claudeclaw/studio'
    | '/settings/api-keys'
    | '/workspaces/$id'
    | '/workspaces'
    | '/agents/free-claude/studio'
    | '/agents/gemini/studio'
    | '/agents/hermes/control'
    | '/agents/hermes/goal'
    | '/agents/hermes/studio'
    | '/agents/hermes/workspace'
    | '/agents/openclaw/studio'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/approvals'
    | '/browser'
    | '/claudeclaw'
    | '/cli'
    | '/demo'
    | '/documents'
    | '/flight-deck'
    | '/goals'
    | '/graphify'
    | '/guide'
    | '/hermes-mcp-loop'
    | '/higgsfield'
    | '/hyperedit'
    | '/hyperframes'
    | '/imported-skills'
    | '/journal'
    | '/kanban'
    | '/kanban-gallery'
    | '/library'
    | '/maestro'
    | '/memory'
    | '/minimax'
    | '/mission-control'
    | '/notebook'
    | '/notes'
    | '/notion'
    | '/org-chart'
    | '/personas'
    | '/pinecone'
    | '/production-unlock'
    | '/prompts'
    | '/replay'
    | '/runtime-registry'
    | '/search-chats'
    | '/seo'
    | '/settings'
    | '/setup'
    | '/share'
    | '/skills'
    | '/studio'
    | '/triad'
    | '/understand'
    | '/video-studio'
    | '/wacrm'
    | '/workforce-os'
    | '/agents/antigravity'
    | '/agents/claude-code'
    | '/agents/claude-code-studio'
    | '/agents/codex'
    | '/agents/free-claude'
    | '/agents/gemini'
    | '/agents/hermes'
    | '/agents/hermes-mcp'
    | '/agents/notebooklm'
    | '/agents/openclaw'
    | '/agents/pi-runtime'
    | '/agents/ruflo'
    | '/agents/slim-charles'
    | '/app/activate'
    | '/claudeclaw/studio'
    | '/settings/api-keys'
    | '/workspaces/$id'
    | '/workspaces/'
    | '/agents/free-claude/studio'
    | '/agents/gemini/studio'
    | '/agents/hermes/control'
    | '/agents/hermes/goal'
    | '/agents/hermes/studio'
    | '/agents/hermes/workspace'
    | '/agents/openclaw/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BrowserRoute: typeof BrowserRoute
  ClaudeclawRoute: typeof ClaudeclawRouteWithChildren
  CliRoute: typeof CliRoute
  DemoRoute: typeof DemoRoute
  DocumentsRoute: typeof DocumentsRoute
  FlightDeckRoute: typeof FlightDeckRoute
  GoalsRoute: typeof GoalsRoute
  GraphifyRoute: typeof GraphifyRoute
  GuideRoute: typeof GuideRoute
  HermesMcpLoopRoute: typeof HermesMcpLoopRoute
  HiggsfieldRoute: typeof HiggsfieldRoute
  HypereditRoute: typeof HypereditRoute
  HyperframesRoute: typeof HyperframesRoute
  ImportedSkillsRoute: typeof ImportedSkillsRoute
  JournalRoute: typeof JournalRoute
  KanbanRoute: typeof KanbanRoute
  KanbanGalleryRoute: typeof KanbanGalleryRoute
  LibraryRoute: typeof LibraryRoute
  MaestroRoute: typeof MaestroRoute
  MemoryRoute: typeof MemoryRoute
  MinimaxRoute: typeof MinimaxRoute
  MissionControlRoute: typeof MissionControlRoute
  NotebookRoute: typeof NotebookRoute
  NotesRoute: typeof NotesRoute
  NotionRoute: typeof NotionRoute
  OrgChartRoute: typeof OrgChartRoute
  PersonasRoute: typeof PersonasRoute
  PineconeRoute: typeof PineconeRoute
  ProductionUnlockRoute: typeof ProductionUnlockRoute
  PromptsRoute: typeof PromptsRoute
  ReplayRoute: typeof ReplayRoute
  RuntimeRegistryRoute: typeof RuntimeRegistryRoute
  SearchChatsRoute: typeof SearchChatsRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  ShareRoute: typeof ShareRoute
  SkillsRoute: typeof SkillsRoute
  StudioRoute: typeof StudioRoute
  TriadRoute: typeof TriadRoute
  UnderstandRoute: typeof UnderstandRoute
  VideoStudioRoute: typeof VideoStudioRoute
  WacrmRoute: typeof WacrmRoute
  WorkforceOsRoute: typeof WorkforceOsRoute
  AgentsAntigravityRoute: typeof AgentsAntigravityRoute
  AgentsClaudeCodeRoute: typeof AgentsClaudeCodeRoute
  AgentsClaudeCodeStudioRoute: typeof AgentsClaudeCodeStudioRoute
  AgentsCodexRoute: typeof AgentsCodexRoute
  AgentsFreeClaudeRoute: typeof AgentsFreeClaudeRouteWithChildren
  AgentsGeminiRoute: typeof AgentsGeminiRouteWithChildren
  AgentsHermesRoute: typeof AgentsHermesRouteWithChildren
  AgentsHermesMcpRoute: typeof AgentsHermesMcpRoute
  AgentsNotebooklmRoute: typeof AgentsNotebooklmRoute
  AgentsOpenclawRoute: typeof AgentsOpenclawRouteWithChildren
  AgentsPiRuntimeRoute: typeof AgentsPiRuntimeRoute
  AgentsRufloRoute: typeof AgentsRufloRoute
  AgentsSlimCharlesRoute: typeof AgentsSlimCharlesRoute
  AppActivateRoute: typeof AppActivateRoute
  WorkspacesIdRoute: typeof WorkspacesIdRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce-os': {
      id: '/workforce-os'
      path: '/workforce-os'
      fullPath: '/workforce-os'
      preLoaderRoute: typeof WorkforceOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wacrm': {
      id: '/wacrm'
      path: '/wacrm'
      fullPath: '/wacrm'
      preLoaderRoute: typeof WacrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-studio': {
      id: '/video-studio'
      path: '/video-studio'
      fullPath: '/video-studio'
      preLoaderRoute: typeof VideoStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triad': {
      id: '/triad'
      path: '/triad'
      fullPath: '/triad'
      preLoaderRoute: typeof TriadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-chats': {
      id: '/search-chats'
      path: '/search-chats'
      fullPath: '/search-chats'
      preLoaderRoute: typeof SearchChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-registry': {
      id: '/runtime-registry'
      path: '/runtime-registry'
      fullPath: '/runtime-registry'
      preLoaderRoute: typeof RuntimeRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-unlock': {
      id: '/production-unlock'
      path: '/production-unlock'
      fullPath: '/production-unlock'
      preLoaderRoute: typeof ProductionUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinecone': {
      id: '/pinecone'
      path: '/pinecone'
      fullPath: '/pinecone'
      preLoaderRoute: typeof PineconeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-chart': {
      id: '/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof OrgChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notion': {
      id: '/notion'
      path: '/notion'
      fullPath: '/notion'
      preLoaderRoute: typeof NotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minimax': {
      id: '/minimax'
      path: '/minimax'
      fullPath: '/minimax'
      preLoaderRoute: typeof MinimaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maestro': {
      id: '/maestro'
      path: '/maestro'
      fullPath: '/maestro'
      preLoaderRoute: typeof MaestroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban-gallery': {
      id: '/kanban-gallery'
      path: '/kanban-gallery'
      fullPath: '/kanban-gallery'
      preLoaderRoute: typeof KanbanGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imported-skills': {
      id: '/imported-skills'
      path: '/imported-skills'
      fullPath: '/imported-skills'
      preLoaderRoute: typeof ImportedSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperframes': {
      id: '/hyperframes'
      path: '/hyperframes'
      fullPath: '/hyperframes'
      preLoaderRoute: typeof HyperframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperedit': {
      id: '/hyperedit'
      path: '/hyperedit'
      fullPath: '/hyperedit'
      preLoaderRoute: typeof HypereditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/higgsfield': {
      id: '/higgsfield'
      path: '/higgsfield'
      fullPath: '/higgsfield'
      preLoaderRoute: typeof HiggsfieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hermes-mcp-loop': {
      id: '/hermes-mcp-loop'
      path: '/hermes-mcp-loop'
      fullPath: '/hermes-mcp-loop'
      preLoaderRoute: typeof HermesMcpLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphify': {
      id: '/graphify'
      path: '/graphify'
      fullPath: '/graphify'
      preLoaderRoute: typeof GraphifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-deck': {
      id: '/flight-deck'
      path: '/flight-deck'
      fullPath: '/flight-deck'
      preLoaderRoute: typeof FlightDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claudeclaw': {
      id: '/claudeclaw'
      path: '/claudeclaw'
      fullPath: '/claudeclaw'
      preLoaderRoute: typeof ClaudeclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browser': {
      id: '/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof BrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$id': {
      id: '/workspaces/$id'
      path: '/workspaces/$id'
      fullPath: '/workspaces/$id'
      preLoaderRoute: typeof WorkspacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/claudeclaw/studio': {
      id: '/claudeclaw/studio'
      path: '/studio'
      fullPath: '/claudeclaw/studio'
      preLoaderRoute: typeof ClaudeclawStudioRouteImport
      parentRoute: typeof ClaudeclawRoute
    }
    '/app/activate': {
      id: '/app/activate'
      path: '/app/activate'
      fullPath: '/app/activate'
      preLoaderRoute: typeof AppActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/slim-charles': {
      id: '/agents/slim-charles'
      path: '/agents/slim-charles'
      fullPath: '/agents/slim-charles'
      preLoaderRoute: typeof AgentsSlimCharlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/ruflo': {
      id: '/agents/ruflo'
      path: '/agents/ruflo'
      fullPath: '/agents/ruflo'
      preLoaderRoute: typeof AgentsRufloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/pi-runtime': {
      id: '/agents/pi-runtime'
      path: '/agents/pi-runtime'
      fullPath: '/agents/pi-runtime'
      preLoaderRoute: typeof AgentsPiRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/openclaw': {
      id: '/agents/openclaw'
      path: '/agents/openclaw'
      fullPath: '/agents/openclaw'
      preLoaderRoute: typeof AgentsOpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/notebooklm': {
      id: '/agents/notebooklm'
      path: '/agents/notebooklm'
      fullPath: '/agents/notebooklm'
      preLoaderRoute: typeof AgentsNotebooklmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/hermes-mcp': {
      id: '/agents/hermes-mcp'
      path: '/agents/hermes-mcp'
      fullPath: '/agents/hermes-mcp'
      preLoaderRoute: typeof AgentsHermesMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/hermes': {
      id: '/agents/hermes'
      path: '/agents/hermes'
      fullPath: '/agents/hermes'
      preLoaderRoute: typeof AgentsHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/gemini': {
      id: '/agents/gemini'
      path: '/agents/gemini'
      fullPath: '/agents/gemini'
      preLoaderRoute: typeof AgentsGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/free-claude': {
      id: '/agents/free-claude'
      path: '/agents/free-claude'
      fullPath: '/agents/free-claude'
      preLoaderRoute: typeof AgentsFreeClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/codex': {
      id: '/agents/codex'
      path: '/agents/codex'
      fullPath: '/agents/codex'
      preLoaderRoute: typeof AgentsCodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/claude-code-studio': {
      id: '/agents/claude-code-studio'
      path: '/agents/claude-code-studio'
      fullPath: '/agents/claude-code-studio'
      preLoaderRoute: typeof AgentsClaudeCodeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/claude-code': {
      id: '/agents/claude-code'
      path: '/agents/claude-code'
      fullPath: '/agents/claude-code'
      preLoaderRoute: typeof AgentsClaudeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/antigravity': {
      id: '/agents/antigravity'
      path: '/agents/antigravity'
      fullPath: '/agents/antigravity'
      preLoaderRoute: typeof AgentsAntigravityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/openclaw/studio': {
      id: '/agents/openclaw/studio'
      path: '/studio'
      fullPath: '/agents/openclaw/studio'
      preLoaderRoute: typeof AgentsOpenclawStudioRouteImport
      parentRoute: typeof AgentsOpenclawRoute
    }
    '/agents/hermes/workspace': {
      id: '/agents/hermes/workspace'
      path: '/workspace'
      fullPath: '/agents/hermes/workspace'
      preLoaderRoute: typeof AgentsHermesWorkspaceRouteImport
      parentRoute: typeof AgentsHermesRoute
    }
    '/agents/hermes/studio': {
      id: '/agents/hermes/studio'
      path: '/studio'
      fullPath: '/agents/hermes/studio'
      preLoaderRoute: typeof AgentsHermesStudioRouteImport
      parentRoute: typeof AgentsHermesRoute
    }
    '/agents/hermes/goal': {
      id: '/agents/hermes/goal'
      path: '/goal'
      fullPath: '/agents/hermes/goal'
      preLoaderRoute: typeof AgentsHermesGoalRouteImport
      parentRoute: typeof AgentsHermesRoute
    }
    '/agents/hermes/control': {
      id: '/agents/hermes/control'
      path: '/control'
      fullPath: '/agents/hermes/control'
      preLoaderRoute: typeof AgentsHermesControlRouteImport
      parentRoute: typeof AgentsHermesRoute
    }
    '/agents/gemini/studio': {
      id: '/agents/gemini/studio'
      path: '/studio'
      fullPath: '/agents/gemini/studio'
      preLoaderRoute: typeof AgentsGeminiStudioRouteImport
      parentRoute: typeof AgentsGeminiRoute
    }
    '/agents/free-claude/studio': {
      id: '/agents/free-claude/studio'
      path: '/studio'
      fullPath: '/agents/free-claude/studio'
      preLoaderRoute: typeof AgentsFreeClaudeStudioRouteImport
      parentRoute: typeof AgentsFreeClaudeRoute
    }
  }
}

interface ClaudeclawRouteChildren {
  ClaudeclawStudioRoute: typeof ClaudeclawStudioRoute
}

const ClaudeclawRouteChildren: ClaudeclawRouteChildren = {
  ClaudeclawStudioRoute: ClaudeclawStudioRoute,
}

const ClaudeclawRouteWithChildren = ClaudeclawRoute._addFileChildren(
  ClaudeclawRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface AgentsFreeClaudeRouteChildren {
  AgentsFreeClaudeStudioRoute: typeof AgentsFreeClaudeStudioRoute
}

const AgentsFreeClaudeRouteChildren: AgentsFreeClaudeRouteChildren = {
  AgentsFreeClaudeStudioRoute: AgentsFreeClaudeStudioRoute,
}

const AgentsFreeClaudeRouteWithChildren =
  AgentsFreeClaudeRoute._addFileChildren(AgentsFreeClaudeRouteChildren)

interface AgentsGeminiRouteChildren {
  AgentsGeminiStudioRoute: typeof AgentsGeminiStudioRoute
}

const AgentsGeminiRouteChildren: AgentsGeminiRouteChildren = {
  AgentsGeminiStudioRoute: AgentsGeminiStudioRoute,
}

const AgentsGeminiRouteWithChildren = AgentsGeminiRoute._addFileChildren(
  AgentsGeminiRouteChildren,
)

interface AgentsHermesRouteChildren {
  AgentsHermesControlRoute: typeof AgentsHermesControlRoute
  AgentsHermesGoalRoute: typeof AgentsHermesGoalRoute
  AgentsHermesStudioRoute: typeof AgentsHermesStudioRoute
  AgentsHermesWorkspaceRoute: typeof AgentsHermesWorkspaceRoute
}

const AgentsHermesRouteChildren: AgentsHermesRouteChildren = {
  AgentsHermesControlRoute: AgentsHermesControlRoute,
  AgentsHermesGoalRoute: AgentsHermesGoalRoute,
  AgentsHermesStudioRoute: AgentsHermesStudioRoute,
  AgentsHermesWorkspaceRoute: AgentsHermesWorkspaceRoute,
}

const AgentsHermesRouteWithChildren = AgentsHermesRoute._addFileChildren(
  AgentsHermesRouteChildren,
)

interface AgentsOpenclawRouteChildren {
  AgentsOpenclawStudioRoute: typeof AgentsOpenclawStudioRoute
}

const AgentsOpenclawRouteChildren: AgentsOpenclawRouteChildren = {
  AgentsOpenclawStudioRoute: AgentsOpenclawStudioRoute,
}

const AgentsOpenclawRouteWithChildren = AgentsOpenclawRoute._addFileChildren(
  AgentsOpenclawRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  BrowserRoute: BrowserRoute,
  ClaudeclawRoute: ClaudeclawRouteWithChildren,
  CliRoute: CliRoute,
  DemoRoute: DemoRoute,
  DocumentsRoute: DocumentsRoute,
  FlightDeckRoute: FlightDeckRoute,
  GoalsRoute: GoalsRoute,
  GraphifyRoute: GraphifyRoute,
  GuideRoute: GuideRoute,
  HermesMcpLoopRoute: HermesMcpLoopRoute,
  HiggsfieldRoute: HiggsfieldRoute,
  HypereditRoute: HypereditRoute,
  HyperframesRoute: HyperframesRoute,
  ImportedSkillsRoute: ImportedSkillsRoute,
  JournalRoute: JournalRoute,
  KanbanRoute: KanbanRoute,
  KanbanGalleryRoute: KanbanGalleryRoute,
  LibraryRoute: LibraryRoute,
  MaestroRoute: MaestroRoute,
  MemoryRoute: MemoryRoute,
  MinimaxRoute: MinimaxRoute,
  MissionControlRoute: MissionControlRoute,
  NotebookRoute: NotebookRoute,
  NotesRoute: NotesRoute,
  NotionRoute: NotionRoute,
  OrgChartRoute: OrgChartRoute,
  PersonasRoute: PersonasRoute,
  PineconeRoute: PineconeRoute,
  ProductionUnlockRoute: ProductionUnlockRoute,
  PromptsRoute: PromptsRoute,
  ReplayRoute: ReplayRoute,
  RuntimeRegistryRoute: RuntimeRegistryRoute,
  SearchChatsRoute: SearchChatsRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  ShareRoute: ShareRoute,
  SkillsRoute: SkillsRoute,
  StudioRoute: StudioRoute,
  TriadRoute: TriadRoute,
  UnderstandRoute: UnderstandRoute,
  VideoStudioRoute: VideoStudioRoute,
  WacrmRoute: WacrmRoute,
  WorkforceOsRoute: WorkforceOsRoute,
  AgentsAntigravityRoute: AgentsAntigravityRoute,
  AgentsClaudeCodeRoute: AgentsClaudeCodeRoute,
  AgentsClaudeCodeStudioRoute: AgentsClaudeCodeStudioRoute,
  AgentsCodexRoute: AgentsCodexRoute,
  AgentsFreeClaudeRoute: AgentsFreeClaudeRouteWithChildren,
  AgentsGeminiRoute: AgentsGeminiRouteWithChildren,
  AgentsHermesRoute: AgentsHermesRouteWithChildren,
  AgentsHermesMcpRoute: AgentsHermesMcpRoute,
  AgentsNotebooklmRoute: AgentsNotebooklmRoute,
  AgentsOpenclawRoute: AgentsOpenclawRouteWithChildren,
  AgentsPiRuntimeRoute: AgentsPiRuntimeRoute,
  AgentsRufloRoute: AgentsRufloRoute,
  AgentsSlimCharlesRoute: AgentsSlimCharlesRoute,
  AppActivateRoute: AppActivateRoute,
  WorkspacesIdRoute: WorkspacesIdRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
