/**
 * Provider catalog — single source of truth for the API Keys / Credentials
 * Manager surface in both Mission Control and Baseline OS.
 *
 * The catalog is data only. No secrets, no live values, no network. It
 * enumerates every provider the platform integrates with so the UI can
 * render "what's missing / what's connected / what unlocks what" and so
 * the encrypted store knows which provider IDs are valid.
 *
 * Adding a provider: append an entry. Bumping the catalog version is
 * NOT required — clients always read the full list.
 */

export type ProviderCategory =
  | 'llm'
  | 'agent_runtime'
  | 'creative_media'
  | 'productivity'
  | 'communication'
  | 'data_search_memory'
  | 'billing'
  | 'devops'
  | 'vertical_api'

export type ProviderImportance = 'required' | 'recommended' | 'optional'

export type ProviderField = {
  /** Stable key used in the encrypted secret JSON or public_config JSON. */
  key: string
  /** UI label. */
  label: string
  /** Field type — drives masking, the form widget, and validation. */
  type: 'secret' | 'text' | 'url' | 'email' | 'password'
  /** Help text below the input. */
  hint?: string
  /** Optional regex the value must match. */
  pattern?: string
  /** Optional placeholder. */
  placeholder?: string
  /** When true the field is optional. */
  optional?: boolean
}

export type ProviderEntry = {
  /** Stable slug; primary key for storage + URLs. */
  id: string
  /** Customer-facing name. */
  name: string
  category: ProviderCategory
  /** Soft tier for the UI's Required / Recommended / Optional grouping. */
  importance: ProviderImportance
  /** Short customer-facing description. */
  description: string
  /** Environment variable names the platform also accepts as a fallback. */
  env_var_names: string[]
  /** Secret fields (encrypted at rest, never returned raw). */
  secret_fields: ProviderField[]
  /** Public config fields (returned as-is to the UI). */
  public_config_fields: ProviderField[]
  /** External URL for signing up / generating the key. */
  setup_url?: string
  /** Documentation URL. */
  docs_url?: string
  /** Whether the platform supports a test-connection probe. */
  test_connection_supported: boolean
  /** Human-readable feature unlock list. */
  required_for_features: string[]
  /**
   * Scope of the credential.
   *   workspace — Mission Control workspace-shared
   *   user      — per-user (BYO key on cloud)
   *   local     — Baseline OS local host
   */
  scope: 'workspace' | 'user' | 'local'
  /**
   * Billing mode this provider participates in.
   *   bring_your_own_key       — operator must provide
   *   mission_control_credits  — covered by MC credits, BYOK optional
   *   both                     — operator chooses per request
   */
  mode: 'bring_your_own_key' | 'mission_control_credits' | 'both'
}

const SECRET = (
  key: string,
  label: string,
  extra: Partial<ProviderField> = {},
): ProviderField => ({ key, label, type: 'secret', ...extra })
const TEXT = (
  key: string,
  label: string,
  extra: Partial<ProviderField> = {},
): ProviderField => ({ key, label, type: 'text', ...extra })

// ─── LLM providers ──────────────────────────────────────────────────
const llm: ProviderEntry[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'llm',
    importance: 'required',
    description: 'GPT family models, embeddings, moderation.',
    env_var_names: ['OPENAI_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'sk-…' })],
    public_config_fields: [TEXT('organization', 'Organization (optional)', { optional: true })],
    setup_url: 'https://platform.openai.com/api-keys',
    docs_url: 'https://platform.openai.com/docs/api-reference',
    test_connection_supported: true,
    required_for_features: ['GPT agents', 'OpenAI embeddings', 'AI summaries', 'OpenAI-backed skills'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    category: 'llm',
    importance: 'required',
    description: 'Claude Opus / Sonnet / Haiku models.',
    env_var_names: ['ANTHROPIC_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'sk-ant-…' })],
    public_config_fields: [],
    setup_url: 'https://console.anthropic.com/settings/keys',
    docs_url: 'https://docs.anthropic.com',
    test_connection_supported: true,
    required_for_features: ['Claude agents', 'Claude Code runtime', 'code review workflows'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'google_gemini',
    name: 'Google Gemini',
    category: 'llm',
    importance: 'recommended',
    description: 'Gemini 2.x / 3.x family — fast frontier reasoning.',
    env_var_names: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'AIza…' })],
    public_config_fields: [],
    setup_url: 'https://aistudio.google.com/app/apikey',
    docs_url: 'https://ai.google.dev/gemini-api/docs',
    test_connection_supported: true,
    required_for_features: ['Gemini Flash agents', 'media/copy workflows', 'Antigravity orchestration'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'groq',
    name: 'Groq',
    category: 'llm',
    importance: 'optional',
    description: 'High-throughput Llama / Mixtral inference.',
    env_var_names: ['GROQ_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'gsk_…' })],
    public_config_fields: [],
    setup_url: 'https://console.groq.com/keys',
    test_connection_supported: true,
    required_for_features: ['Groq-backed agents', 'fast inference fallback'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'llm',
    importance: 'recommended',
    description: 'Multi-model aggregator (OpenAI / Claude / Gemini / open models).',
    env_var_names: ['OPENROUTER_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'sk-or-…' })],
    public_config_fields: [TEXT('base_url', 'Base URL (optional)', { optional: true })],
    setup_url: 'https://openrouter.ai/keys',
    test_connection_supported: true,
    required_for_features: ['Multi-provider agent routing', 'live PAYG balance + burn rate'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'llm',
    importance: 'optional',
    description: 'Live-web reasoning + answer engine.',
    env_var_names: ['PERPLEXITY_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'pplx-…' })],
    public_config_fields: [],
    setup_url: 'https://www.perplexity.ai/settings/api',
    test_connection_supported: true,
    required_for_features: ['Live-web research skills'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    category: 'llm',
    importance: 'optional',
    description: 'Mistral / Mixtral models.',
    env_var_names: ['MISTRAL_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: '…' })],
    public_config_fields: [],
    setup_url: 'https://console.mistral.ai/api-keys',
    test_connection_supported: true,
    required_for_features: ['Mistral agents'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    category: 'llm',
    importance: 'optional',
    description: 'Grok models.',
    env_var_names: ['XAI_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'xai-…' })],
    public_config_fields: [],
    setup_url: 'https://console.x.ai',
    test_connection_supported: true,
    required_for_features: ['xAI-backed agents'],
    scope: 'workspace',
    mode: 'both',
  },
  {
    id: 'ollama',
    name: 'Ollama (local)',
    category: 'llm',
    importance: 'optional',
    description: 'Local model server. No API key — only endpoint URL.',
    env_var_names: ['OLLAMA_HOST'],
    secret_fields: [],
    public_config_fields: [TEXT('endpoint', 'Endpoint URL', { placeholder: 'http://127.0.0.1:11434' })],
    setup_url: 'https://ollama.com',
    test_connection_supported: true,
    required_for_features: ['On-device inference', 'private skill execution'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'lm_studio',
    name: 'LM Studio (local)',
    category: 'llm',
    importance: 'optional',
    description: 'Local OpenAI-compatible model server.',
    env_var_names: ['LM_STUDIO_HOST'],
    secret_fields: [],
    public_config_fields: [TEXT('endpoint', 'Endpoint URL', { placeholder: 'http://127.0.0.1:1234/v1' })],
    setup_url: 'https://lmstudio.ai',
    test_connection_supported: true,
    required_for_features: ['On-device inference'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
]

// ─── Agent / runtime CLIs ──────────────────────────────────────────
const agentRuntime: ProviderEntry[] = [
  {
    id: 'claude_code',
    name: 'Claude Code CLI',
    category: 'agent_runtime',
    importance: 'recommended',
    description: 'Anthropic Claude Code runtime — reads ~/.claude/projects.',
    env_var_names: ['ANTHROPIC_API_KEY'],
    secret_fields: [],
    public_config_fields: [TEXT('cli_path', 'Override CLI path (optional)', { optional: true })],
    setup_url: 'https://docs.anthropic.com/en/docs/claude-code',
    test_connection_supported: true,
    required_for_features: ['Claude Code runtime', 'session ingest', 'skill ROI'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'codex_cli',
    name: 'Codex CLI',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'OpenAI codex command-line agent.',
    env_var_names: ['OPENAI_API_KEY'],
    secret_fields: [],
    public_config_fields: [TEXT('cli_path', 'Override CLI path (optional)', { optional: true })],
    setup_url: 'https://platform.openai.com/docs/codex',
    test_connection_supported: true,
    required_for_features: ['OpenClaw / codex-persona agents'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'openclaw',
    name: 'OpenClaw / OpenCode',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Self-hosted execution runtime.',
    env_var_names: ['OPENCLAW_GATEWAY_URL', 'OPENCLAW_GATEWAY_TOKEN'],
    secret_fields: [SECRET('gateway_token', 'Gateway token')],
    public_config_fields: [TEXT('gateway_url', 'Gateway URL', { placeholder: 'http://127.0.0.1:18789' })],
    setup_url: 'https://github.com/openclaw/openclaw',
    test_connection_supported: true,
    required_for_features: ['OpenClaw swarm dashboard'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'antigravity',
    name: 'Antigravity CLI',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Google DeepMind Antigravity multi-agent CLI (`agy`).',
    env_var_names: ['ANTIGRAVITY_DIR'],
    secret_fields: [],
    public_config_fields: [TEXT('install_dir', 'Antigravity dir (optional)', { optional: true })],
    setup_url: 'https://labs.google.com/antigravity',
    test_connection_supported: true,
    required_for_features: ['Antigravity terminal', 'parallel subagents'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'ruflo',
    name: 'Ruflo',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Ruflo MCP server (200+ agent tools).',
    env_var_names: [],
    secret_fields: [],
    public_config_fields: [TEXT('cli_path', 'Override CLI path (optional)', { optional: true })],
    setup_url: 'https://ruflo.dev',
    test_connection_supported: true,
    required_for_features: ['Ruflo MCP tool catalogue'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'hermes',
    name: 'Hermes',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Long-running orchestration runtime.',
    env_var_names: ['HERMES_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [TEXT('dashboard_url', 'Dashboard URL', { placeholder: 'https://…', optional: true })],
    setup_url: 'https://hermes.dev',
    test_connection_supported: true,
    required_for_features: ['Hermes scheduled pipelines', 'memory consolidation'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'maestro',
    name: 'Maestro',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Mobile UI test agent.',
    env_var_names: ['MAESTRO_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://maestro.mobile.dev',
    test_connection_supported: false,
    required_for_features: ['Mobile UI test workflows'],
    scope: 'local',
    mode: 'bring_your_own_key',
  },
  {
    id: 'browser_use',
    name: 'Browser Use',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'Web-browsing agent.',
    env_var_names: ['BROWSER_USE_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://github.com/browser-use/browser-use',
    test_connection_supported: false,
    required_for_features: ['Browser-driven research'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'notebooklm_agent',
    name: 'NotebookLM Agent',
    category: 'agent_runtime',
    importance: 'optional',
    description: 'NotebookLM workspace agent.',
    env_var_names: ['NOTEBOOKLM_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://notebooklm.google.com',
    test_connection_supported: false,
    required_for_features: ['NotebookLM context skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Creative / media ──────────────────────────────────────────────
const creativeMedia: ProviderEntry[] = [
  {
    id: 'higgsfield',
    name: 'Higgsfield',
    category: 'creative_media',
    importance: 'optional',
    description: 'AI video + image generation.',
    env_var_names: ['HIGGSFIELD_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key')],
    public_config_fields: [],
    setup_url: 'https://higgsfield.ai',
    test_connection_supported: true,
    required_for_features: ['Higgsfield video', 'Higgsfield image workflows'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'hyperframes',
    name: 'HyperFrames',
    category: 'creative_media',
    importance: 'optional',
    description: 'Video Studio render engine.',
    env_var_names: ['HYPERFRAMES_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://hyperframes.ai',
    test_connection_supported: true,
    required_for_features: ['Video Studio render'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'hyperedit',
    name: 'HyperEdit',
    category: 'creative_media',
    importance: 'optional',
    description: 'AI-assisted video editing.',
    env_var_names: ['HYPEREDIT_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://hyperedit.ai',
    test_connection_supported: false,
    required_for_features: ['HyperEdit timeline workflows'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    category: 'creative_media',
    importance: 'optional',
    description: 'MiniMax chat + TTS.',
    env_var_names: ['MINIMAX_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key')],
    public_config_fields: [],
    setup_url: 'https://api.minimax.chat',
    test_connection_supported: true,
    required_for_features: ['MiniMax TTS speech-2.8-hd'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'runway',
    name: 'Runway',
    category: 'creative_media',
    importance: 'optional',
    description: 'Runway Gen-3 / Aleph.',
    env_var_names: ['RUNWAY_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://runwayml.com',
    test_connection_supported: false,
    required_for_features: ['Runway video skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'creative_media',
    importance: 'optional',
    description: 'Voice synthesis + cloning.',
    env_var_names: ['ELEVENLABS_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key')],
    public_config_fields: [],
    setup_url: 'https://elevenlabs.io',
    test_connection_supported: true,
    required_for_features: ['Voice synthesis skills', 'audio briefs'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'pika',
    name: 'Pika',
    category: 'creative_media',
    importance: 'optional',
    description: 'Pika video generation.',
    env_var_names: ['PIKA_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://pika.art',
    test_connection_supported: false,
    required_for_features: ['Pika video skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    category: 'creative_media',
    importance: 'optional',
    description: 'Avatar video generation.',
    env_var_names: ['HEYGEN_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://heygen.com',
    test_connection_supported: false,
    required_for_features: ['Avatar briefing videos'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Google / Productivity ─────────────────────────────────────────
const productivity: ProviderEntry[] = [
  {
    id: 'google_oauth',
    name: 'Google OAuth',
    category: 'productivity',
    importance: 'recommended',
    description: 'OAuth client for Google Sign-In + workspace integrations.',
    env_var_names: ['GOOGLE_OAUTH_CLIENT_ID', 'GOOGLE_OAUTH_CLIENT_SECRET'],
    secret_fields: [SECRET('client_secret', 'OAuth client secret')],
    public_config_fields: [
      TEXT('client_id', 'OAuth client ID'),
      TEXT('redirect_uri', 'Redirect URI', { optional: true }),
    ],
    setup_url: 'https://console.cloud.google.com/apis/credentials',
    test_connection_supported: false,
    required_for_features: ['Sign in with Google', 'Gmail integration', 'Drive integration', 'Calendar integration'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    category: 'productivity',
    importance: 'optional',
    description: 'Drive file reads via OAuth token.',
    env_var_names: [],
    secret_fields: [SECRET('refresh_token', 'OAuth refresh token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://console.cloud.google.com/apis/library/drive.googleapis.com',
    test_connection_supported: true,
    required_for_features: ['Drive file ingest', 'Drive-backed skills'],
    scope: 'user',
    mode: 'bring_your_own_key',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'productivity',
    importance: 'optional',
    description: 'Send + read on behalf of the user.',
    env_var_names: [],
    secret_fields: [SECRET('refresh_token', 'OAuth refresh token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://console.cloud.google.com/apis/library/gmail.googleapis.com',
    test_connection_supported: true,
    required_for_features: ['Gmail intake', 'Customer reply drafting'],
    scope: 'user',
    mode: 'bring_your_own_key',
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    category: 'productivity',
    importance: 'optional',
    description: 'Calendar event read / write.',
    env_var_names: [],
    secret_fields: [SECRET('refresh_token', 'OAuth refresh token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://console.cloud.google.com/apis/library/calendar-json.googleapis.com',
    test_connection_supported: true,
    required_for_features: ['Adjuster scheduling', 'Inspection scheduling', 'Customer appointments'],
    scope: 'user',
    mode: 'bring_your_own_key',
  },
  {
    id: 'google_contacts',
    name: 'Google Contacts',
    category: 'productivity',
    importance: 'optional',
    description: 'Contacts read for routing.',
    env_var_names: [],
    secret_fields: [SECRET('refresh_token', 'OAuth refresh token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://console.cloud.google.com/apis/library/people.googleapis.com',
    test_connection_supported: false,
    required_for_features: ['Contact resolution in skills'],
    scope: 'user',
    mode: 'bring_your_own_key',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    category: 'productivity',
    importance: 'optional',
    description: 'NotebookLM notebooks + chat.',
    env_var_names: ['NOTEBOOKLM_REFRESH_TOKEN'],
    secret_fields: [SECRET('refresh_token', 'Refresh token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://notebooklm.google.com',
    test_connection_supported: false,
    required_for_features: ['NotebookLM tab in Notebook page'],
    scope: 'user',
    mode: 'bring_your_own_key',
  },
]

// ─── Communication ─────────────────────────────────────────────────
const communication: ProviderEntry[] = [
  {
    id: 'telegram_bot',
    name: 'Telegram Bot',
    category: 'communication',
    importance: 'recommended',
    description: 'Approval + alert channel for human-in-the-loop tasks.',
    env_var_names: ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID'],
    secret_fields: [SECRET('bot_token', 'Bot token', { placeholder: '123456:ABC…' })],
    public_config_fields: [TEXT('chat_id', 'Chat ID (your numeric chat id)')],
    setup_url: 'https://t.me/BotFather',
    test_connection_supported: true,
    required_for_features: ['Telegram human approval gate', 'Mobile alerts'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    importance: 'optional',
    description: 'Slack notifications + slash commands.',
    env_var_names: ['SLACK_BOT_TOKEN', 'SLACK_SIGNING_SECRET'],
    secret_fields: [
      SECRET('bot_token', 'Bot token', { placeholder: 'xoxb-…' }),
      SECRET('signing_secret', 'Signing secret', { optional: true }),
    ],
    public_config_fields: [TEXT('default_channel', 'Default channel', { optional: true })],
    setup_url: 'https://api.slack.com/apps',
    test_connection_supported: true,
    required_for_features: ['Slack alerts', 'Slack approvals'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'communication',
    importance: 'optional',
    description: 'Discord bot.',
    env_var_names: ['DISCORD_BOT_TOKEN'],
    secret_fields: [SECRET('bot_token', 'Bot token')],
    public_config_fields: [TEXT('guild_id', 'Guild ID', { optional: true })],
    setup_url: 'https://discord.com/developers/applications',
    test_connection_supported: true,
    required_for_features: ['Discord alerts'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'communication',
    importance: 'optional',
    description: 'SMS + voice.',
    env_var_names: ['TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_FROM'],
    secret_fields: [SECRET('auth_token', 'Auth token')],
    public_config_fields: [
      TEXT('account_sid', 'Account SID'),
      TEXT('from_number', 'From phone number', { placeholder: '+1…' }),
    ],
    setup_url: 'https://console.twilio.com',
    test_connection_supported: true,
    required_for_features: ['SMS approvals', 'Voice alerts'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'retell',
    name: 'Retell',
    category: 'communication',
    importance: 'optional',
    description: 'Voice agent platform.',
    env_var_names: ['RETELL_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://retellai.com',
    test_connection_supported: false,
    required_for_features: ['Retell voice agents'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'vapi',
    name: 'VAPI',
    category: 'communication',
    importance: 'optional',
    description: 'Voice agent platform.',
    env_var_names: ['VAPI_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://vapi.ai',
    test_connection_supported: false,
    required_for_features: ['VAPI voice agents'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'communication',
    importance: 'recommended',
    description: 'Transactional email.',
    env_var_names: ['RESEND_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 're_…' })],
    public_config_fields: [TEXT('from_address', 'From address', { placeholder: 'noreply@example.com' })],
    setup_url: 'https://resend.com/api-keys',
    test_connection_supported: true,
    required_for_features: ['Email invites', 'Daily Brief email', 'Password reset', 'Customer email skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'smtp',
    name: 'SMTP',
    category: 'communication',
    importance: 'optional',
    description: 'Generic SMTP fallback.',
    env_var_names: ['SMTP_HOST', 'SMTP_PORT', 'SMTP_USERNAME', 'SMTP_PASSWORD'],
    secret_fields: [SECRET('password', 'Password')],
    public_config_fields: [
      TEXT('host', 'Host'),
      TEXT('port', 'Port'),
      TEXT('username', 'Username'),
      TEXT('from_address', 'From address'),
    ],
    test_connection_supported: true,
    required_for_features: ['Email fallback'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Data / Search / Memory ────────────────────────────────────────
const dataSearchMemory: ProviderEntry[] = [
  {
    id: 'notion',
    name: 'Notion',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Notion workspace read / write.',
    env_var_names: ['NOTION_API_KEY'],
    secret_fields: [SECRET('api_key', 'Integration secret', { placeholder: 'secret_…' })],
    public_config_fields: [],
    setup_url: 'https://www.notion.so/my-integrations',
    test_connection_supported: true,
    required_for_features: ['Notion-backed skills', 'tenant / owner records'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Hosted vector DB.',
    env_var_names: ['PINECONE_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key')],
    public_config_fields: [TEXT('index', 'Index name', { optional: true })],
    setup_url: 'https://app.pinecone.io',
    test_connection_supported: true,
    required_for_features: ['Vector memory graph'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Hosted Postgres + auth.',
    env_var_names: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    secret_fields: [SECRET('service_role_key', 'Service-role key')],
    public_config_fields: [TEXT('url', 'Project URL', { placeholder: 'https://…supabase.co' })],
    setup_url: 'https://app.supabase.com',
    test_connection_supported: true,
    required_for_features: ['Supabase-backed skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Self-host or cloud vector DB.',
    env_var_names: ['QDRANT_URL', 'QDRANT_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [TEXT('url', 'Endpoint URL', { placeholder: 'http://localhost:6333' })],
    setup_url: 'https://qdrant.tech',
    test_connection_supported: true,
    required_for_features: ['Qdrant vector memory'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Web scraping / crawling.',
    env_var_names: ['FIRECRAWL_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { placeholder: 'fc-…' })],
    public_config_fields: [],
    setup_url: 'https://firecrawl.dev',
    test_connection_supported: true,
    required_for_features: ['Web scrape skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'SERP results API.',
    env_var_names: ['SERPAPI_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key')],
    public_config_fields: [],
    setup_url: 'https://serpapi.com',
    test_connection_supported: true,
    required_for_features: ['SEO research skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'browserbase',
    name: 'Browserbase',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Headless browser as a service.',
    env_var_names: ['BROWSERBASE_API_KEY', 'BROWSERBASE_PROJECT_ID'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [TEXT('project_id', 'Project ID', { optional: true })],
    setup_url: 'https://browserbase.com',
    test_connection_supported: true,
    required_for_features: ['Hosted browser-agent skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'apify',
    name: 'Apify',
    category: 'data_search_memory',
    importance: 'optional',
    description: 'Crawl / scrape platform.',
    env_var_names: ['APIFY_API_TOKEN'],
    secret_fields: [SECRET('api_token', 'API token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://apify.com',
    test_connection_supported: true,
    required_for_features: ['Apify-backed skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Billing / Commerce ────────────────────────────────────────────
const billing: ProviderEntry[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'billing',
    importance: 'required',
    description: 'Credit packs + webhook fulfillment.',
    env_var_names: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
    secret_fields: [
      SECRET('secret_key', 'Secret API key', { placeholder: 'sk_live_…' }),
      SECRET('webhook_secret', 'Webhook signing secret', { placeholder: 'whsec_…' }),
    ],
    public_config_fields: [TEXT('publishable_key', 'Publishable key', { placeholder: 'pk_live_…' })],
    setup_url: 'https://dashboard.stripe.com/apikeys',
    test_connection_supported: true,
    required_for_features: ['Credit packs', 'Checkout', 'Webhook fulfillment'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Deployment / Git / DevOps ─────────────────────────────────────
const devops: ProviderEntry[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'devops',
    importance: 'recommended',
    description: 'Repo access, issues, PR drafting.',
    env_var_names: ['GITHUB_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { placeholder: 'ghp_… or fine-grained' })],
    public_config_fields: [TEXT('default_repo', 'Default repo (owner/repo)', { optional: true })],
    setup_url: 'https://github.com/settings/tokens',
    test_connection_supported: true,
    required_for_features: ['Engineering escalations', 'PR drafting', 'Repo memory'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'devops',
    importance: 'optional',
    description: 'Deploy + observability.',
    env_var_names: ['VERCEL_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [TEXT('team_id', 'Team ID', { optional: true })],
    setup_url: 'https://vercel.com/account/tokens',
    test_connection_supported: true,
    required_for_features: ['Vercel deploy skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: 'devops',
    importance: 'optional',
    description: 'Deploy + edge functions.',
    env_var_names: ['NETLIFY_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://app.netlify.com/user/applications',
    test_connection_supported: true,
    required_for_features: ['Netlify deploy skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    category: 'devops',
    importance: 'optional',
    description: 'Droplets, App Platform, DBs.',
    env_var_names: ['DIGITALOCEAN_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://cloud.digitalocean.com/account/api/tokens',
    test_connection_supported: true,
    required_for_features: ['DO infrastructure skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'docker_registry',
    name: 'Docker registry',
    category: 'devops',
    importance: 'optional',
    description: 'Pull / push container images.',
    env_var_names: ['DOCKER_REGISTRY_USERNAME', 'DOCKER_REGISTRY_PASSWORD'],
    secret_fields: [SECRET('password', 'Password / token', { optional: true })],
    public_config_fields: [TEXT('username', 'Username'), TEXT('registry_url', 'Registry URL', { optional: true })],
    setup_url: 'https://hub.docker.com/settings/security',
    test_connection_supported: false,
    required_for_features: ['Image push / pull skills'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

// ─── Vertical APIs ─────────────────────────────────────────────────
const verticalApi: ProviderEntry[] = [
  {
    id: 'rentcast',
    name: 'Rentcast',
    category: 'vertical_api',
    importance: 'optional',
    description: 'Rental / property data API.',
    env_var_names: ['RENTCAST_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://app.rentcast.io',
    test_connection_supported: true,
    required_for_features: ['Property data lookups', 'Rent estimates'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'zillow_rapidapi',
    name: 'Zillow (RapidAPI)',
    category: 'vertical_api',
    importance: 'optional',
    description: 'Zillow listings via RapidAPI.',
    env_var_names: ['RAPIDAPI_KEY'],
    secret_fields: [SECRET('rapidapi_key', 'RapidAPI key', { optional: true })],
    public_config_fields: [],
    setup_url: 'https://rapidapi.com',
    test_connection_supported: false,
    required_for_features: ['Zillow listing lookups'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'mls_bridge',
    name: 'MLS / Bridge',
    category: 'vertical_api',
    importance: 'optional',
    description: 'MLS / Bridge Interactive feed.',
    env_var_names: ['BRIDGE_API_KEY'],
    secret_fields: [SECRET('api_key', 'API key', { optional: true })],
    public_config_fields: [TEXT('dataset_id', 'Dataset ID', { optional: true })],
    setup_url: 'https://bridgeinteractive.com',
    test_connection_supported: false,
    required_for_features: ['MLS listing ingest'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'propcontrol',
    name: 'PropControl',
    category: 'vertical_api',
    importance: 'optional',
    description: 'PropControl property ops bridge.',
    env_var_names: ['PROPCONTROL_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [TEXT('base_url', 'Base URL', { placeholder: 'https://propcontrolempire.com', optional: true })],
    setup_url: 'https://propcontrolempire.com',
    test_connection_supported: false,
    required_for_features: ['PropControl integration'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'visionops',
    name: 'VisionOps',
    category: 'vertical_api',
    importance: 'optional',
    description: 'VisionOps rehab project bridge.',
    env_var_names: ['VISIONOPS_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [TEXT('base_url', 'Base URL', { placeholder: 'https://rehab-vision.emergent.host', optional: true })],
    setup_url: 'https://rehab-vision.emergent.host',
    test_connection_supported: false,
    required_for_features: ['VisionOps integration'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
  {
    id: 'voiceops',
    name: 'VoiceOps',
    category: 'vertical_api',
    importance: 'optional',
    description: 'VoiceOps voice operations bridge.',
    env_var_names: ['VOICEOPS_TOKEN'],
    secret_fields: [SECRET('token', 'Token', { optional: true })],
    public_config_fields: [TEXT('base_url', 'Base URL', { optional: true })],
    test_connection_supported: false,
    required_for_features: ['VoiceOps integration'],
    scope: 'workspace',
    mode: 'bring_your_own_key',
  },
]

export const PROVIDER_CATALOG: ProviderEntry[] = [
  ...llm,
  ...agentRuntime,
  ...creativeMedia,
  ...productivity,
  ...communication,
  ...dataSearchMemory,
  ...billing,
  ...devops,
  ...verticalApi,
]

export function getProvider(id: string): ProviderEntry | undefined {
  return PROVIDER_CATALOG.find((p) => p.id === id)
}

export function listProvidersByCategory(): Record<ProviderCategory, ProviderEntry[]> {
  const out: Record<ProviderCategory, ProviderEntry[]> = {
    llm: [],
    agent_runtime: [],
    creative_media: [],
    productivity: [],
    communication: [],
    data_search_memory: [],
    billing: [],
    devops: [],
    vertical_api: [],
  }
  for (const p of PROVIDER_CATALOG) out[p.category].push(p)
  return out
}
